"""add fields to User,Class tables

Revision ID: 5a49013dd44c
Revises: 5bf8753faf85
Create Date: 2021-03-07 14:47:30.524882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a49013dd44c'
down_revision = '5bf8753faf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('biography', sa.String(length=1000), nullable=True))
    op.alter_column('users', 'is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'biography')
    op.drop_column('classes', 'date')
    # ### end Alembic commands ###
