"""update user_classes join table

Revision ID: b07098bcdb5a
Revises: e5bbbb32832e
Create Date: 2021-03-14 19:57:15.091860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07098bcdb5a'
down_revision = 'e5bbbb32832e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_classes', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_classes', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
