"""change fields in location table

Revision ID: e5bbbb32832e
Revises: 6a1ad59b753d
Create Date: 2021-03-08 21:23:30.319907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bbbb32832e'
down_revision = '6a1ad59b753d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'lat',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('locations', 'long',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'long',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('locations', 'lat',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
