"""adding location to Class table

Revision ID: 6a1ad59b753d
Revises: 5a49013dd44c
Create Date: 2021-03-07 14:58:15.271227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1ad59b753d'
down_revision = '5a49013dd44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('location', sa.String(), nullable=False))
    op.alter_column('users', 'is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('classes', 'location')
    # ### end Alembic commands ###
